---
all:
  vars:
    cartridge_app_name: cars
    cartridge_package_path: /Users/s.kononenko/Work/xk6-tarantool-example/cars/cars-1.0.0-0.rpm
    cartridge_enable_tarantool_repo: true

    cartridge_cluster_cookie: cars-cluster-cookie
    cartridge_bootstrap_vshard: true

    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_ssh_common_args: '-o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

  hosts:
    router-1:
      config:
        advertise_uri: '172.19.0.2:3301'
        http_port: 8181

    router-2:
      config:
        advertise_uri: '172.19.0.3:3301'
        http_port: 8182

    storage-1:
      config:
        advertise_uri: '172.19.0.2:3302'
        http_port: 8183

    storage-1-replica:
      config:
        advertise_uri: '172.19.0.3:3303'
        http_port: 8184

    storage-2:
      config:
        advertise_uri: '172.19.0.3:3302'
        http_port: 8185

    storage-2-replica:
      config:
        advertise_uri: '172.19.0.2:3303'
        http_port: 8186

  children:
    host1:
      vars:
        ansible_host: 172.19.0.2
        ansible_user: vagrant

      hosts:
        router-1:
        storage-1:
        storage-2-replica:

    host2:
      vars:
        ansible_host: 172.19.0.3
        ansible_user: vagrant

      hosts:
        router-2:
        storage-2:
        storage-1-replica:

    replicaset_router_1:
      vars:
        replicaset_alias: router-1
        roles:
          - 'api'

      hosts:
        router-1:

    replicaset_router_2:
      vars:
        replicaset_alias: router-2
        roles:
          - 'api'

      hosts:
        router-2:

    replicaset_storage_1:
      vars:
        replicaset_alias: storage-1
        roles:
          - 'storage'

      hosts:
        storage-1:
        storage-1-replica:

    replicaset_storage_2:
      vars:
        replicaset_alias: storage-2
        roles:
          - 'storage'

      hosts:
        storage-2:
        storage-2-replica:
